# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Mengjun Leng
email: ch.mengjunleng@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Feel free to contact me!
url: "https://mengjunleng.github.io" # the base hostname & protocol for your site
twitter_username: mengjun
github_username:  connect

# Build settings
markdown: kramdown
